version: "3.9"

services:

# Database Service
  db:
    image: postgres:16-alpine
    container_name: inventorylist_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

# Backend Service
  backend:
    image: node:20-alpine
    container_name: inventorylist_backend
    working_dir: /usr/src/app
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma generate && npm run dev"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/db?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    restart: unless-stopped

# Frontend Service
  frontend:
    image: node:20-alpine
    container_name: inventorylist_frontend
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
